services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: zipflow-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "${MSSQL_SA_PASSWORD:-ChangeThisLocalPassword!1}"
    ports:
      - "1433:1433"
    volumes:
      - zipflow_sql_data:/var/opt/mssql
    restart: unless-stopped

volumes:
  zipflow_sql_data:
